theme: jekyll-theme-slate
title: Mark Sims | research
description: Computational chemistry group at Northumbria <a href="mailto:mark.sims@northumbria.ac.uk"><img src="images/email.png" width="20"></a>
