theme: jekyll-theme-slate
title: Mark Sims | research <img width="150" src="https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D0TC02898C&imageInfo.ImageIdentifier.Year=2020">
description: Computational chemistry at Northumbria

social-network-links:
  email: "mark.sims@northumbria.ac.uk"

og_image: https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D0TC02898C&imageInfo.ImageIdentifier.Year=2020

