theme: jekyll-theme-slate
title: Mark Sims | research
description: Computational chemistry at Northumbria

social-network-links:
  email: "mark.sims@northumbria.ac.uk"
  
<img width="300" src="https://pubs.rsc.org/en/Image/Get?imageInfo.ImageType=GA&imageInfo.ImageIdentifier.ManuscriptID=D0TC02898C&imageInfo.ImageIdentifier.Year=2020">
